### ISSUE TITLE
Should modules have different connections to the DB?

### ISSUE THREAD

**Issue by jgburet** [stemmlerjs/ddd-forum#25]
Thanks a lot for what you're doing here and on "white-label". Very helpful to set right from the beginning new projects!

- On both projects you have several modules. Are they indeed representing different bounded contexts?
- If yes, I was wondering if it wouldn't be a viable option to separate their connections to the DB. Thus having https://github.com/stemmlerjs/ddd-forum/blob/master/src/shared/infra/database/sequelize/config/config.js#L50 exporting a function/factory rather than always the same connection (-pool), making sure nobody ever tries to commit an SQL transaction spanning over several modules.

**Comment by stemmlerjs** [comment]
Hi @jgburet, thanks for your questions!

> On both projects you have several modules. Are they indeed representing different bounded contexts?

I'd like to distinguish between _bounded contexts_ and _subdomains_. This project is deployed as a monolith, so it's a single _bounded context_, but there are two _subdomains_. If we deployed the project in a distributed architecture, we'd have _two bounded contexts_, one for each _subdomain_.

>  I was wondering if it wouldn't be a viable option to separate their connections to the DB

I don't think you'd want to do that. Here's a related issue (https://github.com/stemmlerjs/ddd-forum/issues/36). You would, however, want to do that if you deployed these services (subdomains) as separate bounded contexts though, because you'd be implementing the [database per service](https://microservices.io/patterns/data/database-per-service.html) pattern.

**Comment by jgburet** [comment]
Thanks for your answer :)
