### ISSUE TITLE
Putting ORM Models Inside Modules

### ISSUE THREAD

**Issue by webberwang** [stemmlerjs/ddd-forum#36]
On a conceptual level, would it make more sense to put Sequelize models inside  respective modules in `modules/[module]/infra/*` as opposed to `shared/infra/database/sequelize/models`?

We're co-locating them only because it would be difficult to initialize all models for the ORM? Or do they belong in shared infra folder conceptually?

**Comment by stemmlerjs** [comment]
@webberwang, thanks for your question! There are several completely valid arguments for doing it _either_ way.

Background information here is that Sequelize _does_ want you to have all the modules in a single folder to initialize them, but if we really needed to separate concerns by splitting up the models, that would certainly be a priority. That being said, we've made a conscious decision for this project to build this as a monolith. 

One of the key properties of the monolith is that, while it does have logical boundaries around the services (`users`, `forum`), there is a _single database_ that it relies on. This means that the models for `users` and `forum` are both on the same database instance. That led me to make the decision to put all the models in a _shared_ folder.

Alternatively, one could argue that putting the Sequelize models in the subdomain that they belong could yield a better **developer experience**, because it would mean less flipping between the _shared_ folder and the target _modules_ folder. That's a great argument, and I welcome you to make that decision for yourself. If it works better for you and your team, I think that's an idea. It would, however, mean you have to do a little more stitching to get all the models initialized. You may need to write a script to throw all of the models in a shared folder before initializing Sequelize.

In a truly _distributed architecture_, rather than a monolithic one like this, current best practices are to implement the [Database per service](https://microservices.io/patterns/data/database-per-service.html) pattern. In an architecture like this, we would have not only the logical boundaries but physical ones as well. That means loosely coupled services. In this architecture, a `member` from `forum` knows nothing about a `user` from the `users` subdomain; this complicates transactions across services, but it's a necessary complexity. This project is predominantly about demonstrating the main DDD ideas in practice; hopefully, you're seeing how a distributed architecture would only add to that challenge, and how it influenced the folder structure here.

I hope that was helpful. Let me know if you have any more questions.
