### ISSUE TITLE
[Question]: Why not use Result everywhere?

### ISSUE THREAD

**Issue by ydennisy** [stemmlerjs/ddd-forum#85]
@stemmlerjs hope you are well!

I would like to know why in **repos** you have chosen to try catch and throw Errors.

Yet in most other places you are returning a `Result.fail` or `Result.ok`.

Thanks!

**Comment by hamidgasmi** [comment]
I have the same question.
In `Guard` class, there is another interface for results that is defined (see below). I was expecting to reuse the `Result` class.
```
export interface IGuardResult {
  succeeded: boolean;
  message?: string;
}
```

**Comment by imcyee** [comment]
Because repo implementation is using library that is created by others. 

Look at B: When we encounter errors that we don't expect or know how to deal with. 
These are errors that really mess up what we were trying to do and can be caused by an infinite possibility of things that we didn't expect or assume would happen:

    database connectivity issues
    code typos
    null pointer errors (sometimes)
    out of memory


[When-to-throw-errors-purposefully](https://khalilstemmler.com/articles/enterprise-typescript-nodejs/handling-errors-result-class/#When-to-throw-errors-purposefully)When to throw errors purposefully, in this case the ORM is written by others, and what errors will the ORM throw, very likely those aren't related to your domain, why reporting a no connection as a result?

**Comment by hamidgasmi** [comment]
Agree for the repo. Thanks @imcyee.
I am still wondering why we have multiple `result` classes/interfaces.

**Comment by imcyee** [comment]
I think you definitely can implement it with `Result` class. Don't see any problem with it. Instead of {succeeded:boolean} you will have Result.ok/fail(), from what I learned from his blog, I think this one you have choice to choose between simple json and Result class.

**Comment by stemmlerjs** [comment]
In the name of consistency, I think it's a good idea to use the same construct everywhere. When I first implemented the `Guard` class, I was just using a technique called _programming by wishful thinking_ to design an API that was human-friendly to use. I'm glad you spotted this. Just refactored it to rely on `Result` [here](https://github.com/stemmlerjs/ddd-forum/commit/46e033b32150d5b95586591f3e2cff706e375e4f).

Thanks y'all.
